dprint("this is the band name ganerator\n ")
print("pls enter your city name \n")
city_name=input()
print("pls enter your pet name \n")
pet_name=input()
print("your band name is \n")
print(city_name,pet_name)
